"""Repair-loop orchestration with an explicit state machine."""

from __future__ import annotations

from .decisions import (
    classify_external_blocker,
    should_escalate_to_instrumentation,
    should_stop_test,
)
from .loop import (
    FixLoop,
    LoopSummary,
    TestReport,
    TestResult,
    build_backend,
    default_reporter,
    execute_attempt,
    handle_failed_attempt,
    run_one_test_until_resolved,
    run_repair_loop,
)
from .models import (
    ALL_STATES,
    TERMINAL_STATES,
    RepairDecision,
    RepairRun,
    TestRepairState,
)
from .prompts import (
    build_implementer_prompt,
    build_instrumentation_prompt,
    build_planner_prompt,
)
from .state_machine import (
    EVENT_EXHAUSTED,
    EVENT_EXTERNAL_BLOCKER,
    EVENT_FAIL,
    EVENT_IMPLEMENT,
    EVENT_IMPLEMENTED,
    EVENT_INSTRUMENT,
    EVENT_INSTRUMENTED,
    EVENT_PASS,
    EVENT_PLAN,
    EVENT_PLAN_CREATED,
    EVENT_REGRESS,
    EVENT_RERUN,
    EVENT_START,
    InvalidTransitionError,
    next_state,
    validate_transition,
)
from .store import (
    begin_agent_invocation,
    create_repair_run,
    finish_agent_invocation,
    finish_repair_run,
    has_ever_passed,
    record_agent_invocation,
    record_repair_plan,
    set_plan_outcome,
)

__all__ = [
    "ALL_STATES",
    "EVENT_EXHAUSTED",
    "EVENT_EXTERNAL_BLOCKER",
    "EVENT_FAIL",
    "EVENT_IMPLEMENT",
    "EVENT_IMPLEMENTED",
    "EVENT_INSTRUMENT",
    "EVENT_INSTRUMENTED",
    "EVENT_PASS",
    "EVENT_PLAN",
    "EVENT_PLAN_CREATED",
    "EVENT_REGRESS",
    "EVENT_RERUN",
    "EVENT_START",
    "FixLoop",
    "InvalidTransitionError",
    "LoopSummary",
    "RepairDecision",
    "RepairRun",
    "TERMINAL_STATES",
    "TestRepairState",
    "TestReport",
    "TestResult",
    "begin_agent_invocation",
    "build_backend",
    "build_implementer_prompt",
    "build_instrumentation_prompt",
    "build_planner_prompt",
    "classify_external_blocker",
    "create_repair_run",
    "default_reporter",
    "execute_attempt",
    "finish_agent_invocation",
    "finish_repair_run",
    "handle_failed_attempt",
    "has_ever_passed",
    "next_state",
    "record_agent_invocation",
    "record_repair_plan",
    "run_one_test_until_resolved",
    "run_repair_loop",
    "set_plan_outcome",
    "should_escalate_to_instrumentation",
    "should_stop_test",
    "validate_transition",
]
